config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 get '/locations/:id/approve', to: 'locations#approve', as: 'approve_location'
 get '/events/:id/approve', to: 'events#approve', as: 'approve_event'

  resources :locations do
    resources :favorites, only: [:create]
  end
  resources :events do
    resources :favorites, only: [:create]
  end

  resources :ratings
  resources :favorites, only: [:index, :destroy]
  resources :cities
  resources :neighborhoods
  resources :profiles, only: [:show, :edit, :update]
  resources :search, only: :index
  # resources :locations
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="d-flex flex-wrapalign-items-center border-top d-flex justify-content-center py-3 my-5">
    <%= image_tag "logo-txt-vert.svg" %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-wh-txt-hor.svg" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# <li class="nav-item active"> %>
            <%# <%= link_to "Home", "#", class: "nav-link" %>
          <%# </li> %>
          <%# <li class="nav-item"> %>
            <%# <%= link_to "Messages", "#", class: "nav-link" %>
          <%# </li> %>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.admin %>
              <%= image_tag "https://res.cloudinary.com/go-local/image/upload/v1694204361/avatar/Eu_quadrada_p0vmhu.jpg", class: "avatar", alt: "dropdown menu" %>
            <% else %>
              <%= image_tag "https://res.cloudinary.com/go-local/image/upload/v1694180913/avatar/WhatsApp_Image_2023-03-14_at_15.23.58_kw8jzm.jpg", class: "avatar", alt: "dropdown menu" %>
            <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Meu Perfil", profile_path(current_user), class: "dropdown-item" %>
              <%= link_to "Meus favoritos", favorites_path, class: "dropdown-item" %>
              <%= link_to "Adicionar um evento", new_event_path, class: "dropdown-item" %>
              <%= link_to "Adicionar um local", new_location_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Entrar", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>