config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 get '/locations/:id/approve', to: 'locations#approve', as: 'approve_location'
 get '/events/:id/approve', to: 'events#approve', as: 'approve_event'

  resources :locations do
    resources :favorites, only: [:create]
  end
  resources :events do
    resources :favorites, only: [:create]
  end

  resources :ratings
  resources :favorites, only: [:index, :destroy]
  resources :cities
  resources :neighborhoods
  resources :profiles, only: [:show, :edit, :update]
  resources :search, only: :index
  # resources :locations
end

app/models/event.rb
class Event < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search, against: [:title], using: :trigram
  belongs_to :user
  belongs_to :location
  has_one_attached :photo
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :approve]

  def index
    @events = policy_scope(Event).where(approved: true)
  end

  def show
    authorize @event
    @event_id = @event.id
    @location = @event.location
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @event.approved = false if @event.approved.nil?
    authorize @event
    if @event.save
      redirect_to event_path(@event), notice: "Evento criado com sucesso!"
    else
      render :new
    end
  end

  def edit
    authorize @event
  end

  def update
    authorize @event
    if @event.update(event_params)
      redirect_to event_path, notice: "Evento atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to events_path, notice: "Evento excluido com sucesso!"
  end

  def approve
    authorize @event
    @event.approved = true
    if @event.save!
      redirect_to profile_path(current_user), notice: "Evento aprovado com sucesso!"
    else
      redirect_to event_path
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :location_id, :user_id, :neighborhood_id, :photo, :approved)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/views/events/_form.html.erb
  <%= form_with(model: event, class: "edit-form") do |f| %>
    <%= f.label :title, "Título do evento" %>
    <%= f.text_field :title %>
    <%= f.label :date, "Data do evento" %>
    <%= f.datetime_local_field :date %>
    <%= f.label :location_id, "Selecione o local do evento" %>
    <%= f.select :location_id, Location.order(:name).map { |location| [location.name, location.id] } %>
    <%= f.label :description, "Descrição do evento" %>
    <%= f.text_area :description %>
    <%= f.file_field :photo %>
    <%= f.submit "Enviar", class: "btn btn-flat" %>
  <% end %>

app/views/events/edit.html.erb
<h1>Editar <%= @event.title %></h1>
<div>
  <%= render "form", event: @event %>
</div>

app/views/events/index.html.erb
<h1>Todos os eventos</h1>
  <div class="" >
    <%= render "shared/cards/card_event", elements: @events %>
  </div>

app/views/events/new.html.erb
<h1>Cadastre um novo evento</h1>
<div>
  <%= render "form", event: @event %>
</div>

app/views/events/show.html.erb
<section>
  <span class="d-flex align-items-baseline">
    <h1><%= @event.title %></h1>
    <h2><%= @event.location.name %></h2>
  </span>
  <div class="d-flex align-items-center justify-content-between">
    <h4><%= @event.date.strftime("%A, %d %B, %Y - %H:%M") %></h4>
    <div class="d-flex align-items-center">
      <% if current_user && current_user.favorites.where(event_id: @event.id).exists? %>
        <i class="fa fa-heart favorited-heart"></i>
      <% else %>
        <%= link_to event_favorites_path(@event), data: {turbo_method: :post} do %>
          <span class="favoritar-text no-style-link">Favoritar</span><i class="fa fa-heart"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <p class="mt-2"><%= @event.description %></p>
  <div class="d-flex justify-content-between mt-3">
    <% if user_signed_in? %>
      <div>
        <% if policy(@event).edit? %>
          <%= link_to "Editar evento", edit_event_path, class: "btn-main" %>
        <% end %>
        <% if policy(@event).approve? && @event.approved = false %>
          <%= link_to "Aprovar evento", approve_event_path(@event) , class: "btn-main" %>
        <% end %>
        <% if policy(@event).destroy? %>
          <%= link_to "Excluir evento", event_path(@event), data: { turbo_method: :delete, turbo_confirm: "Tem certeza que gostaria de apagar esse evento?" }, class: "btn-sub" %>
        <% end %>
      </div>
      <div>
        <%= link_to "Todos os eventos", events_path, class: "btn-main" %>
      </div>
    <% else %>
      <div>
        <%= link_to "Todos os eventos", events_path, class: "btn-main" %>
      </div>
    <% end %>
  </div>
</section>