config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 get '/locations/:id/approve', to: 'locations#approve', as: 'approve_location'
 get '/events/:id/approve', to: 'events#approve', as: 'approve_event'

  resources :locations do
    resources :favorites, only: [:create]
  end
  resources :events do
    resources :favorites, only: [:create]
  end

  resources :ratings
  resources :favorites, only: [:index, :destroy]
  resources :cities
  resources :neighborhoods
  resources :profiles, only: [:show, :edit, :update]
  resources :search, only: :index
  # resources :locations
end

app/views/shared/cards/_card_category.html.erb
<div class="grid-card-category">
  <% elements.each do |category| %>
    <% if category == "Café" %>
      <% image_url = "https://res.cloudinary.com/go-local/image/upload/v1693959984/categories/cafe_upnhne.jpg" %>
    <% elsif category == "Bar" %>
      <% image_url = "https://res.cloudinary.com/go-local/image/upload/v1693959984/categories/bar_bqnrmr.jpg" %>
    <% elsif category == "Parque" %>
      <% image_url = "https://res.cloudinary.com/go-local/image/upload/v1693959984/categories/park_kdtxoo.jpg" %>
    <% elsif category == "Loja" %>
      <% image_url = "https://res.cloudinary.com/go-local/image/upload/v1693959984/categories/loja_sj9lar.jpg" %>
    <% elsif category == "Restaurante" %>
      <% image_url = "https://res.cloudinary.com/go-local/image/upload/v1693959985/categories/restaurant_kv96mc.jpg" %>
    <% elsif category == "Museu" %>
      <% image_url = "https://res.cloudinary.com/go-local/image/upload/v1693959984/categories/museu_icxbzl.jpg" %>
    <% end %>
    <%= link_to locations_path(category: category, city: @city || nil, neighborhood: @neighborhood || nil),
                                class: "card-category text-decoration-none",
                                style: "background-image: url('#{image_url}');" do %>
      <div class="card-category-content">
        <%= category %>
      </div>
    <% end %>
  <% end %>
</div>
<%# <% asset_url = asset_path("teste-sp.png") %>
<%# , style: "background-image: url('#{asset_url}');" %>

app/views/shared/cards/_card_city.html.erb
<div class="grid-card-city">
  <% elements.each do |element| %>
    <% asset_url = element.photo.url %>
    <% path_url = city_path(element.id) %>
    <%= link_to path_url, class: "card-city", style: "background-image: url('#{asset_url}');"  do %>
      <div class="card-city-content">
        <%= element.name %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/cards/_card_event.html.erb
<div class="grid-card-event">
  <% @events.each do |event| %>
    <%= link_to event_path(event), class: "card-event sq-md" do %>
      <div class="card-event-img">
        <% asset_url = event.photo.url %>
        <%= image_tag asset_path(asset_url) %>
      </div>
      <div class="card-event-content">
        <div class="card-event-date">
          <%= event.date.strftime('%d/%m/%Y') %>
        </div>
        <div class="card-event-title clamp-2">
          <h4><%= event.title %></h4>
        </div>
        <div class="card-event-description clamp-2">
          <%= event.description %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/cards/_card_location.html.erb
<div class="grid-card-location">
  <% @locations.each do |location| %>
    <%= link_to location_path(location), class: "card-location" do %>
      <div class="card-location-img" style="background-image: url('<%= location.photo.url %>');" ></div>
      <div class="card-location-content">
        <div class="card-location-title clamp-2">
          <h4><%= location.name %></h4>
        </div>
        <div class="card-location-description clamp-2">
          <%= location.description %>
        </div>
        <div class="card-location-description clamp-2">
          <p><%= location.address %></p> 
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/cards/_card_neighborhood.html.erb
<div class="grid-card-neighborhood">
  <% elements.each do |element| %>
    <% asset_url = element.photo.url %>
    <% path_url = city_path(element.id) %>
    <%= link_to neighborhood_path(element), class: "card-neighborhood", style: "background-image: url('#{asset_url}');" do %>
      <div class="card-neighborhood-content p-5">
        <%= element.name %>
      </div>
    <% end %>
  <% end %>
</div>