config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 get '/locations/:id/approve', to: 'locations#approve', as: 'approve_location'
 get '/events/:id/approve', to: 'events#approve', as: 'approve_event'

  resources :locations do
    resources :favorites, only: [:create]
  end
  resources :events do
    resources :favorites, only: [:create]
  end

  resources :ratings
  resources :favorites, only: [:index, :destroy]
  resources :cities
  resources :neighborhoods
  resources :profiles, only: [:show, :edit, :update]
  resources :search, only: :index
  # resources :locations
end

app/models/location.rb
class Location < ApplicationRecord
  include PgSearch::Model
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  pg_search_scope :search, against: [:name], using: {
    tsearch: {prefix: true}
   }
  belongs_to :user
  belongs_to :neighborhood
  has_many :events
  has_many :ratings
  has_one_attached :photo
  has_many :favorites

  def self.categories
    ["Café", "Parque", "Bar", "Loja", "Restaurante", "Museu"]
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy, :approve]
  
  def index
    @category = params[:category]
    @city_id = params[:city]
    @neighborhood_id = params[:neighborhood]
    @neighborhood = Neighborhood.where("neighborhood.id = ?", @neighborhood_id)
    @locations = policy_scope(Location).where(approved: true)
    if @category.present?
      if @city_id.present?
        @locations = @locations.joins(neighborhood: :city).where(category: @category).where("cities.id = ?", @city_id)
      elsif @neighborhood_id.present?
        @locations = @locations.where(category: @category).where(neighborhood_id: @neighborhood_id)
      else
        @locations = @locations.where(category: @category)
      end
    else
      @locations
    end
    @markers = @locations.geocoded.map do |location|
      {
        id: location.id,
        lat: location.latitude,
        lng: location.longitude,
        info_window_html: render_to_string(partial: "locations/info_window", locals: { location: location }),
        marker_html: render_to_string(partial: "locations/marker")
      }
    end
    render layout: "map_page"
  end

  def show
    authorize @location
    @neighborhood = @location.neighborhood
    @marker = {
      id: @location.id,
      lat: @location.latitude,
      lng: @location.longitude,
      info_window_html: render_to_string(partial: "locations/info_window", locals: { location: @location }),
      marker_html: render_to_string(partial: "locations/marker")
    }
    @location = Location.find(params[:id])
    @location_id = @location.id
  end

  def new
    @location = Location.new
    authorize @location
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user
    @location.approved = false if @location.approved.nil?
    authorize @location
    if @location.save
      redirect_to location_path(@location), notice: "Local criado com sucesso!"
    else
      render :new
    end
  end

  def edit
    authorize @location
  end

  def update
    authorize @location
    if @location.update(location_params)
      redirect_to location_path, notice: "Local atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    authorize @location
    @location.destroy
    redirect_to locations_path, notice: "Local excluido com sucesso!"
  end

  def approve
    authorize @location
    @location.approved = true
    if @location.save!
      redirect_to profile_path(current_user), notice: "Local aprovado com sucesso!"
    else
      redirect_to location_path
    end
  end

  # def toggle_favorite
  #   Rails.logger.debug "toggle_favorite called"
  #   @location = Location.find(params[:id])
  #   favorite = current_user.favorites.find_by(location_id: @location.id)

  #   if favorite
  #     favorite.destroy!
  #     render json: { favorited: false }
  #   else
  #     new_favorite = current_user.favorites.new(location_id: @location.id)
  #     if new_favorite.save
  #       render json: { favorited: true }
  #     else
  #       render json: { error: new_favorite.errors.full_messages }, status: :unprocessable_entity
  #     end
  #   end
  # end

  private

  def location_params
    params.require(:location).permit(:name, :address, :description, :neighborhood_id, :category, :photo, :approved)
  end

  def set_location
    @location = Location.find(params[:id])
  end
end

app/views/locations/_banner.html.erb
<div class="banner-home" style="background-image: url('<%= image_url(@location.photo.url) %>');" >

app/views/locations/_form.html.erb
  <%= form_with(model: @location, class: "edit-form") do |f| %>
    <%= f.label :name, "Nome do local" %>
    <%= f.text_field :name, class: "mb-3 border-radius-input"  %>
    <%= f.label :address, "Endereço completo" %>
    <%= f.text_field :address, class: "mb-3 border-radius-input" %>
    <%= f.label :neighborhood_id, "Selecione o bairro" %>
    <%= f.select :neighborhood_id, Neighborhood.order(:name).map { |neighborhood| [neighborhood.name, neighborhood.id] }, class: "border-radius-input" %>
    <%= f.label :category, "Selecione o tipo de local", class: "mt-3" %>
    <%= f.select :category, Location.categories, class: "mb-3 border-radius-input" %>
    <%= f.label :description, "Descrição do local", class: "mt-3" %>
    <%= f.text_area :description, class: "mb-3 border-radius-input"  %>
    <%= f.file_field :photo, class: "mb-5" %>
    <%= f.submit "Enviar", class: "btn btn-main" %>
  <% end %>

app/views/locations/_info_window.html.erb
<!-- Div pai com posicionamento relativo -->
<div class="card-event-wrapper">
  <!-- Div da imagem -->
  <div class="card-event-img"></div>
<h2><%= location.name %></h2>
<p><%= location.address %></p>

  <!-- Ícone do coração com posicionamento absoluto -->
  <div class="heart-icon">
     <% if current_user && current_user.favorites.where(location_id: location.id).exists? %>
      <i class="fa fa-heart favorited-heart"></i>

    <% else %>
      <%= link_to location_favorites_path(location), data: {turbo_method: :post} do %>
        <i class="fa fa-heart"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/locations/_marker.html.erb
<%= image_tag "pin.png", height: 30, width: 30, alt: "Logo", class: "map-marker" %>

app/views/locations/edit.html.erb
<h1>Editar <%= @location.name %></h1>
<div>
  <%= render "form", event: @location %>
</div>

app/views/locations/index.html.erb
<div class="row">
  <!-- Left: Location Cards -->
  <div class="col-md-6">
    <h1 class="map-page-heading"><%= @category %></h1>
    <div class="overflow-auto scrollable-content" style="height: 100vh;">
      <div class="d-flex flex-column locations-container-geo">
        <!-- Title -->
        <div class="grid-card-event-geo sq-md pr-5 pl-5">
          <% @locations.each do |location| %>
            <% asset_url = location.photo.url %>
            <%= link_to location_path(location), class: "map-marker-link location-link text-decoration-none", data: { id: location.id } do %>
              <div class="card-location-img-geo" data-action="mouseover->map#highlightMarker mouseout->map#unhighlightMarker" style="background-image: url('<%= asset_url %>');"></div>
              <div class="card-geo sq-md" data-id="<%= location.id %>" data-lat="<%= location.latitude %>" data-lng="<%= location.longitude %>">
                <div class="card-content-geo sq-md" data-action="mouseover->map#highlightMarker mouseout->map#unhighlightMarker">
                  <div>
                    <h5><%= location.name %></h5>
                  </div>
                  <div class="card-address link-text">
                    <%= location.address %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <!-- Right: Map -->
  <div class="col-md-6">
    <div class="fixed-map">
      <div class="location-map" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>

app/views/locations/new.html.erb
<div class="h-auto login-page">
  <div class="text-center mb-5">
    <h2>Cadastrar local</h2>
  </div>
  <div class="form-inputs login-form m-auto">
    <%= render "form", event: @location %>
  </div>
</div>

app/views/locations/show.html.erb
<section class="position-relative mb-3">
  <div class="heart-icon-geo position-absolute special-heart-position d-flex align-items-baseline">
    <% if current_user && current_user.favorites.where(location_id: @location.id).exists? %>
      <i class="fa fa-heart favorited-heart"></i>
    <% else %>
      <%= link_to location_favorites_path(@location), data: {turbo_method: :post} do %>
       <i class="fa fa-heart ml-3"></i><span class="favoritar-text no-style-link link-text"> Favoritar</span>
      <% end %>
    <% end %>
  </div>
  <span class="d-flex align-items-baseline">
    <h1><%= @location.name %></h1>
    <h2><%= @neighborhood.name %></h2>
  </span>
  <span class="location-address"><%= @location.address %></span>
</section>

<section class="location-address mb-5">
  <%= render "banner" %>
</section>

<div class="d-flex gap-5">
  <div class="location-description w-50">
    <p class="mr-4"><%= @location.description %></p>
  </div>
  <!-- Map -->
  <div class="location-map-show w-50 vh-25" data-controller="map"
        data-map-markers-value="<%= [@marker].to_json %>"
       data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" >
  </div>
</div>
<div>
  <div class="d-flex justify-content-end mt-3 gap-2">
    <% if user_signed_in? %>
      <% unless @location.approved %>
        <% if policy(@location).approve? %>
          <%= link_to "Aprovar local",  approve_location_path(@location) , class: "btn-main" %>
        <% end %>
      <% end %>
      <% if policy(@location).edit? %>
        <%= link_to "Editar local", edit_location_path, class: "btn-sub mr-5 " %>
      <% end %>
      <% if policy(@location).destroy? %>
        <%= link_to "Excluir local", location_path(@location), data: { turbo_method: :delete, turbo_confirm: "Tem certeza que gostaria de apagar esse local?" }, class: "btn-sub" %>
      <% end %>
    <% else %>
      <%= link_to "Todos os locais", locations_path, class: "btn-sub" %>
    <% end %>
  </div>
</div>